# generate client keys
---
- name: Copy openssl extensions
  copy:
    src: openssl-client.ext
    dest: "{{openvpn_key_dir}}"
    owner: root
    group: root
    mode: 0400

- name: generate client key
  command: openssl req -nodes -newkey rsa:{{openvpn_rsa_bits}} -keyout {{item}}.key -out {{item}}.csr -days 3650 -subj /CN=OpenVPN-Client-{{inventory_hostname}}-{{item}}/
    chdir="{{openvpn_key_dir}}"
    creates={{item}}.key
  with_items: "{{clients}}"

- name: sign client key
  command: openssl x509 -req -in {{item}}.csr -out {{item}}.crt -CA ca.crt -CAkey ca-key.pem -sha256 -days 3650 -extfile openssl-client.ext
    chdir="{{openvpn_key_dir}}"
    creates={{item}}.crt
  with_items: "{{clients}}"

- name: Generate unified client conf
  include: unified_client_conf.yml
  when: openvpn_generate_unified_client_conf

- name: Generate client conf + keys
  include: separate_client_conf.yml
  when: not openvpn_generate_unified_client_conf
