- name: Enable firewalld
  service:
    name: firewalld
    enabled: true
    state: started

- name: Enable OpenVPN Port (firewalld)
  firewalld:
    port: "{{openvpn_port}}/{{openvpn_proto}}"
    state: enabled
    permanent: yes
    zone: "{{firewalld_default_interface_zone}}"
    immediate: yes

- name: Set tun0 interface to internal
  firewalld:
    interface: tun0
    zone: internal
    permanent: true

- name: Set default interface to external
  firewalld:
    interface: "{{ansible_default_ipv4.interface}}"
    zone: "{{firewalld_default_interface_zone}}"
    permanent: true

- name: Enable masquerading on external zone
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true
    zone: "{{firewalld_default_interface_zone}}"

# workaround for --permanent not working on non-NetworkManager managed ifaces
# https://bugzilla.redhat.com/show_bug.cgi?id=1112742
- name: Check if ifcfg-{{ansible_default_ipv4.interface}} exists
  stat:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ansible_default_ipv4.interface}}"
  register: ifcfg

- name: Persist default interface in ifcfg file
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ansible_default_ipv4.interface}}
    regexp: "^ZONE="
    line: "ZONE={{firewalld_default_interface_zone}}"
  when: ifcfg.stat.exists
