- name: Install openvpn
  package: >
   name={{item}}
   state=present
  with_items:
    - openvpn
    - openssl

- name: Install iptables-persistent (Debian/Ubuntu)
  apt: >
    name=iptables-persistent
    state=present
  when: ansible_pkg_mgr == "apt"

# RHEL has the group 'nobody', 'Debian/Ubuntu' have 'nogroup'
# standardize on 'nogroup'
- name: Ensure group 'nogroup' is present
  group: >
    name=nogroup
    state=present
    system=yes
