- name: register server ca key
  slurp:
    src: "{{openvpn_key_dir}}/ca.crt"
  register: ca_cert

- name: register tls-auth key
  slurp:
    src: "{{openvpn_key_dir}}/ta.key"
  register: tls_auth

- name: register client certs
  slurp:
    src: "{{openvpn_key_dir}}/{{item}}.crt"
  with_items: "{{clients}}"
  register: client_certs

- name: register client keys
  slurp: src: "{{openvpn_key_dir}}/{{item}}.key"
  with_items: "{{clients}}"
  register: client_keys

- name: generate client config
  template:
    src: client.ovpn.j2
    dest: /etc/openvpn/{{item.0.item}}-{{inventory_hostname}}.ovpn
    owner: root
    group: root
    mode: 0400
  with_together:
    - "{{client_certs.results}}"
    - "{{client_keys.results}}"

- name: fetch client config
  fetch:
    src: /etc/openvpn/{{item}}-{{inventory_hostname}}.ovpn
    dest: {{openvpn_local_dest_dir}}/{{item}}/{{inventory_hostname}}.ovpn
    flat: yes
  with_items: "{{clients}}"
